"""Nagios configuration generator: MariaDB (desired state) -> object files.

The generator never touches live Nagios files. It produces an in-memory set
of files which pipeline.py writes into a staging directory together with a
manifest (SHA-256 of every file) that the privileged scripts verify.
"""
from __future__ import annotations

import base64
import hashlib
import json
import re
from dataclasses import dataclass, field

from sqlalchemy import select
from sqlalchemy.orm import Session

from .. import validators as V
from ..config import get_settings
from ..models import Command, Contact, ContactGroup, Server, ServerGroup, SystemSetting
from ..security import crypto
from .legacy import LegacyConfig

HEADER = (
    "###############################################################################\n"
    "# Generated by Nagios Management Portal - DO NOT EDIT BY HAND.\n"
    "# This file is replaced on every configuration apply. Make changes in the portal.\n"
    "###############################################################################\n\n"
)

HOST_TEMPLATES = {
    "windows": "nmp-windows-host",
    "linux": "nmp-linux-host",
    "unix": "nmp-linux-host",
    "network": "nmp-network-host",
    "other": "nmp-generic-host",
}

TEMPLATES_CFG = """define host {
    name                            nmp-generic-host
    notifications_enabled           1
    event_handler_enabled           1
    flap_detection_enabled          1
    process_perf_data               1
    retain_status_information       1
    retain_nonstatus_information    0
    check_period                    24x7
    notification_period             24x7
    notification_options            d,u,r
    notification_interval           60
    max_check_attempts              5
    check_interval                  5
    retry_interval                  1
    register                        0
}

define host {
    name                            nmp-windows-host
    use                             nmp-generic-host
    register                        0
}

define host {
    name                            nmp-linux-host
    use                             nmp-generic-host
    register                        0
}

define host {
    name                            nmp-network-host
    use                             nmp-generic-host
    register                        0
}

define service {
    name                            nmp-generic-service
    active_checks_enabled           1
    passive_checks_enabled          1
    parallelize_check               1
    obsess_over_service             0
    check_freshness                 0
    notifications_enabled           1
    event_handler_enabled           1
    flap_detection_enabled          1
    process_perf_data               1
    retain_status_information       1
    retain_nonstatus_information    0
    is_volatile                     0
    check_period                    24x7
    max_check_attempts              3
    check_interval                  5
    retry_interval                  1
    notification_options            w,u,c,r
    notification_interval           60
    notification_period             24x7
    register                        0
}
"""

_TOKEN_RE = re.compile(r"\{([a-z_]+)\}")
_OPT_RE = re.compile(r"\[\[(.*?)\]\]")


class GenerationError(Exception):
    pass


@dataclass
class Generated:
    files: dict[str, str] = field(default_factory=dict)
    secrets: dict[str, str] = field(default_factory=dict)
    expected_hosts: list[str] = field(default_factory=list)
    errors: list[dict] = field(default_factory=list)
    warnings: list[dict] = field(default_factory=list)
    stats: dict[str, int] = field(default_factory=dict)

    @property
    def config_hash(self) -> str:
        h = hashlib.sha256()
        for path in sorted(self.files):
            h.update(path.encode())
            h.update(b"\0")
            h.update(self.files[path].encode())
            h.update(b"\0")
        return h.hexdigest()


def nagios_escape(value: str) -> str:
    """Literal '$' must be doubled inside Nagios command arguments."""
    return value.replace("$", "$$")


def render_args(template: str, values: dict[str, str]) -> str:
    for k, v in values.items():
        if v and any(ch in v for ch in "!\n\r;`"):
            raise GenerationError(f"unsafe character in value '{k}'")

    def opt(m: re.Match) -> str:
        seg = m.group(1)
        toks = _TOKEN_RE.findall(seg)
        if all(values.get(t) for t in toks):
            return _TOKEN_RE.sub(lambda t: values[t.group(1)], seg)
        return ""

    out = _OPT_RE.sub(opt, template)

    def req(m: re.Match) -> str:
        t = m.group(1)
        if not values.get(t):
            raise GenerationError(f"required value '{t}' is empty")
        return values[t]

    out = _TOKEN_RE.sub(req, out)
    return re.sub(r"\s+", " ", out).strip()


def service_description_from(template: str, params: dict[str, str]) -> str:
    try:
        return _TOKEN_RE.sub(lambda m: params.get(m.group(1), ""), template).strip()
    except Exception:
        return template


def _line(key: str, value) -> str:
    return f"    {key:<32}{value}\n"


def _block(otype: str, items: list[tuple[str, object]]) -> str:
    body = "".join(_line(k, v) for k, v in items if v is not None and v != "")
    return f"define {otype} {{\n{body}}}\n\n"


def _setting(db: Session, key: str, default):
    row = db.get(SystemSetting, key)
    return row.value if row is not None else default


def active_servers(db: Session) -> list[Server]:
    q = select(Server).where(
        Server.deleted_token == 0,
        Server.managed_by == "portal",
        Server.config_state != "draft",
    ).order_by(Server.hostname)
    return list(db.scalars(q))


def build_check_values(threshold_w: str | None, threshold_c: str | None, schema: list[dict],
                       params: dict) -> dict[str, str]:
    values = V.validate_params(schema, params)
    for p in schema:
        if p["type"] == "mount":
            values[f"{p['name']}_ncpa"] = values[p["name"]].replace("/", "|") if values[p["name"]] else ""
        if p["type"] == "drive" and values.get(p["name"]):
            values[p["name"]] = values[p["name"]].upper()
    values = {k: nagios_escape(v) for k, v in values.items()}
    values["warning"] = V.check_threshold(threshold_w, "warning") or ""
    values["critical"] = V.check_threshold(threshold_c, "critical") or ""
    return values


def generate(db: Session, legacy: LegacyConfig | None = None, takeover_hosts: set[str] | None = None) -> Generated:
    """Generate the complete managed configuration from the database."""
    g = Generated()
    s = get_settings()
    takeover_hosts = takeover_hosts or set()
    legacy_hosts = legacy.names("host", "host_name") - takeover_hosts if legacy else set()
    legacy_commands = legacy.names("command", "command_name") if legacy else set()
    legacy_hostgroups = legacy.names("hostgroup", "hostgroup_name") if legacy else set()
    legacy_cgroups = legacy.names("contactgroup", "contactgroup_name") if legacy else set()
    legacy_contacts = legacy.names("contact", "contact_name") if legacy else set()
    legacy_tp = legacy.names("timeperiod", "timeperiod_name") if legacy else set()

    def err(obj: str, msg: str, suggestion: str | None = None, file: str | None = None):
        g.errors.append({"object": obj, "message": msg, "suggestion": suggestion, "file": file, "line": None})

    # ---- commands --------------------------------------------------------
    parts = [HEADER]
    commands = list(db.scalars(select(Command).order_by(Command.name)))
    for c in commands:
        if c.name in legacy_commands:
            err(f"command '{c.name}'", "a command with this name already exists in manual configuration",
                "Rename the portal command.")
        cl = (c.command_line.replace("{NMP}", s.plugin_dir_nmp).replace("{STD}", s.plugin_dir_std)
              .replace("{NCPA}", s.plugin_dir_ncpa))
        parts.append(_block("command", [("command_name", c.name), ("command_line", cl)]))
    g.files["commands/nmp-commands.cfg"] = "".join(parts)
    g.files["templates/nmp-templates.cfg"] = HEADER + TEMPLATES_CFG

    # ---- host groups -----------------------------------------------------
    parts = [HEADER]
    known_hostgroups = set(legacy_hostgroups)
    for grp in db.scalars(select(ServerGroup).order_by(ServerGroup.name)):
        known_hostgroups.add(grp.name)
        if not grp.is_managed:
            if legacy and grp.name not in legacy_hostgroups:
                g.warnings.append({"object": f"hostgroup '{grp.name}'",
                                   "message": "external host group is not defined in manual configuration"})
            continue
        if grp.name in legacy_hostgroups:
            err(f"hostgroup '{grp.name}'", "host group already defined in manual configuration",
                "Mark the group as external (not managed) or rename it.")
        parts.append(_block("hostgroup", [("hostgroup_name", grp.name), ("alias", grp.alias)]))
    g.files["hostgroups/nmp-hostgroups.cfg"] = "".join(parts)

    # ---- contacts ------------------------------------------------------------
    parts = [HEADER]
    host_cmd = _setting(db, "host_notification_command", "notify-host-by-email")
    svc_cmd = _setting(db, "service_notification_command", "notify-service-by-email")
    known_cgroups = set(legacy_cgroups)
    for ct in db.scalars(select(Contact).where(Contact.is_managed.is_(True)).order_by(Contact.name)):
        if ct.name in legacy_contacts:
            err(f"contact '{ct.name}'", "contact already defined in manual configuration")
        parts.append(_block("contact", [
            ("contact_name", ct.name), ("alias", ct.alias), ("email", ct.email), ("pager", ct.phone),
            ("host_notifications_enabled", 1 if ct.is_enabled else 0),
            ("service_notifications_enabled", 1 if ct.is_enabled else 0),
            ("host_notification_period", ct.notification_period),
            ("service_notification_period", ct.notification_period),
            ("host_notification_options", ct.host_notification_options),
            ("service_notification_options", ct.service_notification_options),
            ("host_notification_commands", host_cmd), ("service_notification_commands", svc_cmd),
        ]))
    for cg in db.scalars(select(ContactGroup).order_by(ContactGroup.name)):
        known_cgroups.add(cg.name)
        if not cg.is_managed:
            continue
        if cg.name in legacy_cgroups:
            err(f"contactgroup '{cg.name}'", "contact group already defined in manual configuration")
        members = ",".join(sorted(m.name for m in cg.members))
        parts.append(_block("contactgroup", [("contactgroup_name", cg.name), ("alias", cg.alias),
                                             ("members", members or None)]))
    g.files["contacts/nmp-contacts.cfg"] = "".join(parts)

    default_cg = _setting(db, "default_contact_group", "admins")

    # ---- hosts & services ------------------------------------------------------
    secret_lines: list[str] = []
    n_services = 0
    for srv in active_servers(db):
        hn = srv.hostname
        obj = f"host '{hn}'"
        try:
            V.check_hostname(hn)
            V.check_address(srv.address)
        except V.ValidationError as exc:
            err(obj, exc.message)
            continue
        if hn in legacy_hosts:
            err(obj, "a host with this name is already defined in manual configuration",
                "Use Import > Take over to migrate the existing definition, or choose another hostname.")
            continue
        for tp in (srv.check_period, srv.notification_period):
            if legacy is not None and tp not in legacy_tp:
                err(obj, f"time period '{tp}' is not defined", "Use an existing time period such as 24x7.")
        cgs = [c.name for c in srv.contact_groups] or ([default_cg] if default_cg else [])
        for c in cgs:
            if c not in known_cgroups:
                err(obj, f"contact group '{c}' does not exist", "Create it or pick another contact group.")
        hgs = [grp.name for grp in srv.groups]
        for hgname in hgs:
            if hgname not in known_hostgroups:
                err(obj, f"host group '{hgname}' does not exist")
        cred = {c.credential_type: c for c in srv.credentials}
        method = srv.monitoring_method
        custom_vars: list[tuple[str, object]] = [("_NMP_KEY", srv.nagios_key)]
        if method == "ncpa":
            c = cred.get("ncpa")
            if c is None or not c.secret_ciphertext:
                err(obj, "NCPA token is not configured", "Edit the server and enter the NCPA token.")
                continue
            try:
                token = crypto.decrypt_json(c.secret_ciphertext, f"cred:ncpa").get("token")
            except crypto.CryptoError:
                err(obj, "stored NCPA token cannot be decrypted (master key changed?)", "Re-enter the token.")
                continue
            secret_lines.append(_secret_line(srv.nagios_key, "ncpa", {"token": token}))
            custom_vars += [("_NCPA_PORT", c.port or 5693), ("_NCPA_TIMEOUT", c.timeout or 30),
                            ("_NCPA_SSL", "verify" if c.verify_ssl else "noverify")]
            host_cmd_line = "nmp_check_ncpa!-M system/agent_version" if srv.host_check == "agent" else "nmp_check_host_alive"
        elif method == "snmp":
            c = cred.get("snmp")
            if c is None or not c.secret_ciphertext:
                err(obj, "SNMP credentials are not configured", "Edit the device and enter SNMP credentials.")
                continue
            try:
                data = crypto.decrypt_json(c.secret_ciphertext, "cred:snmp")
            except crypto.CryptoError:
                err(obj, "stored SNMP credentials cannot be decrypted", "Re-enter the credentials.")
                continue
            data.update({"version": c.snmp_version or "2c", "username": c.snmp_username or "",
                         "auth_protocol": c.snmp_auth_protocol or "", "priv_protocol": c.snmp_priv_protocol or "",
                         "security_level": c.snmp_security_level or "authPriv"})
            secret_lines.append(_secret_line(srv.nagios_key, "snmp", data))
            host_cmd_line = "nmp_check_snmp!--mode uptime" if srv.host_check == "agent" else "nmp_check_host_alive"
        elif method == "nrpe":
            c = cred.get("nrpe")
            custom_vars += [("_NRPE_PORT", (c.port if c and c.port else 5666)),
                            ("_NRPE_TIMEOUT", (c.timeout if c else 30))]
            host_cmd_line = "nmp_check_tcp!" + str(c.port if c and c.port else 5666) if srv.host_check == "agent" else "nmp_check_host_alive"
        else:
            host_cmd_line = "nmp_check_host_alive"

        notes = " | ".join(x for x in [
            f"Env: {srv.environment}", f"Location: {srv.location}" if srv.location else "",
            f"OS: {srv.os_type}{(' ' + srv.os_version) if srv.os_version else ''}",
        ] if x)
        enabled = 1 if srv.is_enabled else 0
        host_items: list[tuple[str, object]] = [
            ("use", HOST_TEMPLATES.get(srv.os_type, "nmp-generic-host")),
            ("host_name", hn), ("alias", srv.display_name), ("display_name", srv.display_name),
            ("address", srv.address), ("hostgroups", ",".join(hgs) or None),
            ("contact_groups", ",".join(cgs) or None), ("check_command", host_cmd_line),
            ("max_check_attempts", srv.max_check_attempts), ("check_interval", srv.check_interval),
            ("retry_interval", srv.retry_interval), ("check_period", srv.check_period),
            ("notification_period", srv.notification_period),
            ("notification_interval", srv.notification_interval),
            ("notifications_enabled", 1 if (srv.notifications_enabled and enabled) else 0),
            ("active_checks_enabled", enabled), ("notes", notes),
        ] + custom_vars
        g.files[f"hosts/{hn}.cfg"] = HEADER + _block("host", host_items)
        g.expected_hosts.append(hn)

        svc_parts = [HEADER]
        seen_desc: set[str] = set()
        for ss in srv.services:
            if not ss.is_enabled:
                continue
            cat = ss.service
            sobj = f"service '{ss.service_description}' on host '{hn}'"
            try:
                V.check_service_description(ss.service_description)
                if ss.service_description in seen_desc:
                    raise V.ValidationError("service_description", "duplicate service description")
                seen_desc.add(ss.service_description)
                th = ss.threshold
                w = th.warning if th else cat.default_warning
                c_ = th.critical if th else cat.default_critical
                values = build_check_values(w, c_, cat.params_schema, ss.params)
                args = render_args(cat.arg_template, values)
            except (V.ValidationError, GenerationError) as exc:
                err(sobj, str(exc))
                continue
            check = cat.command.name + (f"!{args}" if args else "")
            svc_parts.append(_block("service", [
                ("use", "nmp-generic-service"), ("host_name", hn),
                ("service_description", ss.service_description), ("check_command", check),
                ("max_check_attempts", th.max_check_attempts if th else 3),
                ("check_interval", th.check_interval if th else cat.default_check_interval),
                ("retry_interval", th.retry_interval if th else cat.default_retry_interval),
                ("notification_interval", th.notification_interval if th else cat.default_notification_interval),
                ("notifications_enabled", 1 if ((th.notifications_enabled if th else True) and enabled and srv.notifications_enabled) else 0),
                ("active_checks_enabled", enabled),
                ("_NMP_SVC_ID", ss.id),
            ]))
            n_services += 1
        g.files[f"services/{hn}.cfg"] = "".join(svc_parts)

    g.secrets["nmp-secrets.tsv"] = "".join(secret_lines)
    g.stats = {"hosts": len(g.expected_hosts), "services": n_services, "commands": len(commands)}
    return g


def _secret_line(key: str, kind: str, data: dict) -> str:
    blob = base64.b64encode(json.dumps(data, separators=(",", ":")).encode()).decode()
    return f"{key}\t{kind}\t{blob}\n"
