import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Pencil, Plus, Trash2 } from "lucide-react";
import { ApiError, api } from "../lib/api";
import { useAuth } from "../lib/auth";
import { OS_TYPES, METHODS, methodLabel, osLabel } from "../lib/format";
import { Alert, Card, Checkbox, DataTable, ErrorBox, Field, Loading, Modal, PageHeader, useUi, type Column } from "../components/ui";

/* Generic helpers ---------------------------------------------------------- */
function useCrud(key: string, url: string) {
  const qc = useQueryClient();
  const { toast, confirm, apiError } = useUi();
  const q = useQuery({ queryKey: [key], queryFn: () => api.get(url) });
  const save = async (item: any, body: any) => {
    const r = item?.id ? await api.put(`${url}/${item.id}`, body) : await api.post(url, body);
    toast("success", item?.id ? "Saved" : "Created");
    qc.invalidateQueries({ queryKey: [key] });
    qc.invalidateQueries({ queryKey: ["pending"] });
    return r;
  };
  const remove = async (item: any, label: string) => {
    if (!(await confirm({ title: "Delete", message: `Delete ${label}?`, danger: true, confirmLabel: "Delete" }))) return;
    try { await api.del(`${url}/${item.id}`); toast("success", "Deleted"); qc.invalidateQueries({ queryKey: [key] }); }
    catch (e) { apiError(e, "Delete failed"); }
  };
  return { q, save, remove, rows: (q.data?.data ?? []) as any[], meta: q.data?.meta };
}

function EditModal({ title, onClose, onSave, children, size }: { title: string; onClose: () => void; onSave: () => Promise<void>; children: React.ReactNode; size?: "wide" | "xwide" }) {
  const [err, setErr] = useState<unknown>(null);
  const [busy, setBusy] = useState(false);
  const go = async () => { setBusy(true); setErr(null); try { await onSave(); onClose(); } catch (e) { setErr(e); } finally { setBusy(false); } };
  return (
    <Modal title={title} onClose={onClose} size={size} footer={<><button className="btn" onClick={onClose}>Cancel</button><button className="btn primary" disabled={busy} onClick={go}>Save</button></>}>
      <div className="stack">{err ? <ErrorBox error={err} /> : null}{children}</div>
    </Modal>
  );
}

const fe = (err: unknown, f: string) => (err instanceof ApiError ? err.fieldErrors()[f] : undefined);

function RowButtons({ onEdit, onDelete, canEdit, canDelete }: { onEdit?: () => void; onDelete?: () => void; canEdit: boolean; canDelete: boolean }) {
  return (
    <span className="row" style={{ justifyContent: "flex-end", flexWrap: "nowrap" }}>
      {canEdit && onEdit && <button className="btn sm ghost" aria-label="Edit" onClick={(e) => { e.stopPropagation(); onEdit(); }}><Pencil size={14} /></button>}
      {canDelete && onDelete && <button className="btn sm ghost" aria-label="Delete" onClick={(e) => { e.stopPropagation(); onDelete(); }}><Trash2 size={14} /></button>}
    </span>
  );
}

const Managed = ({ v }: { v: boolean }) => (v ? <span className="badge info">Portal</span> : <span className="badge outline" title="Defined in manual Nagios configuration">Manual</span>);

/* Host groups -------------------------------------------------------------- */
export function HostGroupsPage() {
  const { can } = useAuth();
  const c = useCrud("hostgroups", "/api/hostgroups");
  const [edit, setEdit] = useState<any>(null);
  const cols: Column<any>[] = [
    { key: "name", header: "Name" }, { key: "alias", header: "Alias" }, { key: "description", header: "Description" },
    { key: "members", header: "Servers", className: "num" }, { key: "is_managed", header: "Managed by", render: (r) => <Managed v={r.is_managed} /> },
    { key: "a", header: "", sortable: false, className: "actions", render: (r) => <RowButtons canEdit={can("groups.manage") && r.is_managed} canDelete={can("groups.manage")} onEdit={() => setEdit(r)} onDelete={() => c.remove(r, `host group ${r.name}`)} /> },
  ];
  return (
    <div>
      <PageHeader title="Host groups" subtitle="Groups generated by the portal plus groups found in your existing Nagios files (manual)." actions={can("groups.manage") && <button className="btn primary" onClick={() => setEdit({})}><Plus size={15} />New host group</button>} />
      <ErrorBox error={c.q.error} />
      <Card flush>{c.q.isLoading ? <Loading /> : <DataTable rows={c.rows} columns={cols} rowKey={(r) => r.id} />}</Card>
      {edit && <GroupForm item={edit} onClose={() => setEdit(null)} save={c.save} />}
    </div>
  );
}
function GroupForm({ item, onClose, save }: any) {
  const [v, setV] = useState({ name: item.name ?? "", alias: item.alias ?? "", description: item.description ?? "" });
  return (
    <EditModal title={item.id ? `Edit ${item.name}` : "New host group"} onClose={onClose} onSave={() => save(item, { ...v, description: v.description || null })}>
      <Field label="Name" required hint="Nagios hostgroup_name; cannot be changed later."><input className="input" disabled={!!item.id} value={v.name} onChange={(e) => setV({ ...v, name: e.target.value })} /></Field>
      <Field label="Alias" required><input className="input" value={v.alias} onChange={(e) => setV({ ...v, alias: e.target.value })} /></Field>
      <Field label="Description"><input className="input" value={v.description} onChange={(e) => setV({ ...v, description: e.target.value })} /></Field>
    </EditModal>
  );
}

/* Templates ---------------------------------------------------------------- */
export function TemplatesPage() {
  const { can } = useAuth();
  const c = useCrud("templates", "/api/templates");
  const catalog = useQuery({ queryKey: ["catalog"], queryFn: () => api.get("/api/services") });
  const [edit, setEdit] = useState<any>(null);
  const cols: Column<any>[] = [
    { key: "name", header: "Template", render: (r) => <><strong>{r.name}</strong>{r.is_system && <span className="badge outline" style={{ marginLeft: 6 }}>Built-in</span>}<div className="faint small">{r.description}</div></> },
    { key: "os_type", header: "OS", render: (r) => osLabel(r.os_type) }, { key: "monitoring_method", header: "Method", render: (r) => methodLabel(r.monitoring_method) },
    { key: "items", header: "Services", sortValue: (r) => r.items.length, render: (r) => <div>{r.items.map((i: any) => <span className="tag" key={i.id}>{i.service_description}</span>)}</div> },
    { key: "usage", header: "Used by", className: "num" },
    { key: "a", header: "", sortable: false, className: "actions", render: (r) => <RowButtons canEdit={can("templates.manage")} canDelete={can("templates.manage")} onEdit={() => setEdit(r)} onDelete={() => c.remove(r, `template ${r.name}`)} /> },
  ];
  return (
    <div>
      <PageHeader title="Monitoring templates" subtitle="Reusable service sets applied when adding servers. Changing a template does not change servers already created from it."
        actions={can("templates.manage") && <button className="btn primary" onClick={() => setEdit({ items: [], os_type: "windows", monitoring_method: "ncpa" })}><Plus size={15} />New template</button>} />
      <Card flush>{c.q.isLoading ? <Loading /> : <DataTable rows={c.rows} columns={cols} rowKey={(r) => r.id} />}</Card>
      {edit && <TemplateForm item={edit} catalog={catalog.data?.data ?? []} onClose={() => setEdit(null)} save={c.save} />}
    </div>
  );
}
function TemplateForm({ item, catalog, onClose, save }: any) {
  const [v, setV] = useState({ name: item.name ?? "", description: item.description ?? "", os_type: item.os_type, monitoring_method: item.monitoring_method });
  const [items, setItems] = useState<any[]>(item.items.map((i: any) => ({ ...i })));
  const [add, setAdd] = useState("");
  const avail = catalog.filter((s: any) => s.os_types.includes(v.os_type));
  const byId = Object.fromEntries(catalog.map((s: any) => [s.id, s]));
  return (
    <EditModal size="xwide" title={item.id ? `Edit template ${item.name}` : "New template"} onClose={onClose}
      onSave={() => save(item, { ...v, description: v.description || null, items: items.map((i) => ({ service_id: i.service_id, service_description: i.service_description, params: i.params, warning: i.warning || null, critical: i.critical || null, check_interval: i.check_interval || null, retry_interval: i.retry_interval || null, notification_interval: i.notification_interval ?? null, notifications_enabled: i.notifications_enabled ?? true })) })}>
      <div className="form-grid">
        <Field label="Name" required><input className="input" value={v.name} onChange={(e) => setV({ ...v, name: e.target.value })} /></Field>
        <Field label="Description"><input className="input" value={v.description} onChange={(e) => setV({ ...v, description: e.target.value })} /></Field>
        <Field label="Operating system"><select className="input" value={v.os_type} onChange={(e) => setV({ ...v, os_type: e.target.value })}>{OS_TYPES.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}</select></Field>
        <Field label="Monitoring method"><select className="input" value={v.monitoring_method} onChange={(e) => setV({ ...v, monitoring_method: e.target.value })}>{METHODS.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}</select></Field>
      </div>
      <table className="table">
        <thead><tr><th>Service description</th><th>Definition</th><th>Parameters (JSON-free: key=value)</th><th>Warning</th><th>Critical</th><th /></tr></thead>
        <tbody>{items.map((i, idx) => {
          const s = byId[i.service_id];
          return (
            <tr key={idx}>
              <td><input className="input sm" value={i.service_description} onChange={(e) => setItems(items.map((x, j) => (j === idx ? { ...x, service_description: e.target.value } : x)))} /></td>
              <td className="small">{s?.name}</td>
              <td><div className="row">{(s?.params_schema ?? []).map((p: any) => (
                <input key={p.name} className="input sm" style={{ width: 130 }} placeholder={p.label} value={i.params?.[p.name] ?? ""} onChange={(e) => setItems(items.map((x, j) => (j === idx ? { ...x, params: { ...x.params, [p.name]: e.target.value } } : x)))} />))}</div></td>
              <td><input className="input sm" style={{ width: 90 }} value={i.warning ?? ""} onChange={(e) => setItems(items.map((x, j) => (j === idx ? { ...x, warning: e.target.value } : x)))} /></td>
              <td><input className="input sm" style={{ width: 90 }} value={i.critical ?? ""} onChange={(e) => setItems(items.map((x, j) => (j === idx ? { ...x, critical: e.target.value } : x)))} /></td>
              <td className="actions"><button className="btn sm ghost" onClick={() => setItems(items.filter((_, j) => j !== idx))}><Trash2 size={14} /></button></td>
            </tr>
          );
        })}</tbody>
      </table>
      <div className="row">
        <select className="input" style={{ maxWidth: 320 }} value={add} onChange={(e) => setAdd(e.target.value)}><option value="">Add a service...</option>{avail.map((s: any) => <option key={s.id} value={s.id}>{s.name} ({methodLabel(s.monitoring_method)})</option>)}</select>
        <button className="btn" disabled={!add} onClick={() => { const s = byId[Number(add)]; const params: any = {}; s.params_schema.forEach((p: any) => { params[p.name] = p.default ?? ""; });
          setItems([...items, { service_id: s.id, service_description: s.default_description.replace(/\{([a-z_]+)\}/g, (_: string, k: string) => params[k] ?? ""), params, warning: s.default_warning ?? "", critical: s.default_critical ?? "" }]); setAdd(""); }}><Plus size={14} />Add</button>
      </div>
    </EditModal>
  );
}

/* Service definitions ----------------------------------------------------- */
export function ServiceDefsPage() {
  const { can } = useAuth();
  const c = useCrud("catalog", "/api/services");
  const cmds = useQuery({ queryKey: ["commands"], queryFn: () => api.get("/api/commands") });
  const [edit, setEdit] = useState<any>(null);
  const cols: Column<any>[] = [
    { key: "name", header: "Service", render: (r) => <><strong>{r.name}</strong>{r.is_system && <span className="badge outline" style={{ marginLeft: 6 }}>Built-in</span>}<div className="faint small">{r.description}</div></> },
    { key: "code", header: "Code", render: (r) => <code>{r.code}</code> }, { key: "category", header: "Category" },
    { key: "monitoring_method", header: "Method", render: (r) => methodLabel(r.monitoring_method) },
    { key: "os_types", header: "OS", sortable: false, render: (r) => r.os_types.map((o: string) => <span className="tag" key={o}>{osLabel(o)}</span>) },
    { key: "command_name", header: "Command / arguments", render: (r) => <span className="mono small">{r.command_name}!{r.arg_template}</span> },
    { key: "defaults", header: "Defaults (W / C)", sortable: false, render: (r) => `${r.default_warning ?? "-"} / ${r.default_critical ?? "-"}` },
    { key: "usage", header: "In use", className: "num" },
    { key: "a", header: "", sortable: false, className: "actions", render: (r) => <RowButtons canEdit={can("catalog.manage")} canDelete={can("catalog.manage") && !r.is_system} onEdit={() => setEdit(r)} onDelete={() => c.remove(r, r.name)} /> },
  ];
  return (
    <div>
      <PageHeader title="Service definitions" subtitle="Check definitions used by servers and templates. Arguments are rendered from validated parameters; free-form shell is never allowed."
        actions={can("catalog.manage") && <button className="btn primary" onClick={() => setEdit({ params_schema: [], os_types: ["windows"], monitoring_method: "ncpa", category: "custom", default_check_interval: 5, default_retry_interval: 1, default_notification_interval: 60 })}><Plus size={15} />New definition</button>} />
      <Card flush>{c.q.isLoading ? <Loading /> : <DataTable rows={c.rows} columns={cols} rowKey={(r) => r.id} pageSize={50} />}</Card>
      {edit && <ServiceDefForm item={edit} commands={cmds.data?.data ?? []} paramTypes={c.meta?.param_types ?? []} onClose={() => setEdit(null)} save={c.save} />}
    </div>
  );
}
function ServiceDefForm({ item, commands, paramTypes, onClose, save }: any) {
  const [v, setV] = useState<any>({ ...item, command_id: item.command_id ?? commands[0]?.id });
  const [params, setParams] = useState<any[]>(item.params_schema ?? []);
  const sys = !!item.is_system;
  const body = () => {
    const out: any = {}; for (const k of ["code", "name", "category", "monitoring_method", "os_types", "command_id", "arg_template", "default_description", "default_warning", "default_critical", "default_check_interval", "default_retry_interval", "default_notification_interval", "unit", "description"]) out[k] = v[k] === "" ? null : v[k];
    out.arg_template = v.arg_template ?? ""; out.params_schema = params; return out;
  };
  return (
    <EditModal size="wide" title={item.id ? `Edit ${item.name}` : "New service definition"} onClose={onClose} onSave={() => save(item, body())}>
      {sys && <Alert kind="info">Built-in definition: only the argument template and defaults can be changed.</Alert>}
      <div className="form-grid">
        <Field label="Code" required hint="lowercase identifier"><input className="input" disabled={sys || !!item.id} value={v.code ?? ""} onChange={(e) => setV({ ...v, code: e.target.value })} /></Field>
        <Field label="Name" required><input className="input" disabled={sys} value={v.name ?? ""} onChange={(e) => setV({ ...v, name: e.target.value })} /></Field>
        <Field label="Category"><select className="input" disabled={sys} value={v.category} onChange={(e) => setV({ ...v, category: e.target.value })}>{["availability", "cpu", "memory", "disk", "processes", "services", "network", "uptime", "eventlog", "users", "custom"].map((c) => <option key={c}>{c}</option>)}</select></Field>
        <Field label="Method"><select className="input" disabled={sys} value={v.monitoring_method} onChange={(e) => setV({ ...v, monitoring_method: e.target.value })}>{METHODS.map((m) => <option key={m.value} value={m.value}>{m.label}</option>)}</select></Field>
        <Field label="Command"><select className="input" disabled={sys} value={v.command_id} onChange={(e) => setV({ ...v, command_id: Number(e.target.value) })}>{commands.map((c: any) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></Field>
        <Field label="Operating systems"><div className="row">{OS_TYPES.map((o) => <Checkbox key={o.value} disabled={sys} checked={v.os_types.includes(o.value)} label={o.label} onChange={(c) => setV({ ...v, os_types: c ? [...v.os_types, o.value] : v.os_types.filter((x: string) => x !== o.value) })} />)}</div></Field>
        <Field label="Argument template" span2 hint="Tokens: {param}, {warning}, {critical}; optional segment [[ -x {param}]]. Separate ARGn with !."><input className="input mono" value={v.arg_template ?? ""} onChange={(e) => setV({ ...v, arg_template: e.target.value })} /></Field>
        <Field label="Default service description" hint="May use {param}"><input className="input" disabled={sys} value={v.default_description ?? ""} onChange={(e) => setV({ ...v, default_description: e.target.value })} /></Field>
        <Field label="Unit"><input className="input" disabled={sys} value={v.unit ?? ""} onChange={(e) => setV({ ...v, unit: e.target.value })} /></Field>
        <Field label="Default warning"><input className="input" value={v.default_warning ?? ""} onChange={(e) => setV({ ...v, default_warning: e.target.value })} /></Field>
        <Field label="Default critical"><input className="input" value={v.default_critical ?? ""} onChange={(e) => setV({ ...v, default_critical: e.target.value })} /></Field>
        <Field label="Check / retry / notification interval (min)"><div className="row"><input className="input" type="number" style={{ width: 80 }} value={v.default_check_interval} onChange={(e) => setV({ ...v, default_check_interval: Number(e.target.value) })} /><input className="input" type="number" style={{ width: 80 }} value={v.default_retry_interval} onChange={(e) => setV({ ...v, default_retry_interval: Number(e.target.value) })} /><input className="input" type="number" style={{ width: 80 }} value={v.default_notification_interval} onChange={(e) => setV({ ...v, default_notification_interval: Number(e.target.value) })} /></div></Field>
        <Field label="Description"><input className="input" value={v.description ?? ""} onChange={(e) => setV({ ...v, description: e.target.value })} /></Field>
      </div>
      {!sys && (<>
        <h3>Parameters</h3>
        {params.map((p, i) => (
          <div className="row" key={i}>
            <input className="input sm" style={{ width: 130 }} placeholder="name" value={p.name} onChange={(e) => setParams(params.map((x, j) => (j === i ? { ...x, name: e.target.value } : x)))} />
            <select className="input sm" style={{ width: 130 }} value={p.type} onChange={(e) => setParams(params.map((x, j) => (j === i ? { ...x, type: e.target.value } : x)))}>{paramTypes.map((t: string) => <option key={t}>{t}</option>)}</select>
            <input className="input sm" style={{ width: 180 }} placeholder="label" value={p.label} onChange={(e) => setParams(params.map((x, j) => (j === i ? { ...x, label: e.target.value } : x)))} />
            <input className="input sm" style={{ width: 110 }} placeholder="default" value={p.default ?? ""} onChange={(e) => setParams(params.map((x, j) => (j === i ? { ...x, default: e.target.value || null } : x)))} />
            <Checkbox checked={!!p.required} onChange={(c) => setParams(params.map((x, j) => (j === i ? { ...x, required: c } : x)))} label="required" />
            <button className="btn sm ghost" onClick={() => setParams(params.filter((_, j) => j !== i))}><Trash2 size={14} /></button>
          </div>
        ))}
        <div><button className="btn sm" onClick={() => setParams([...params, { name: "", type: "text", label: "", required: false }])}><Plus size={14} />Add parameter</button></div>
      </>)}
    </EditModal>
  );
}

/* Commands ----------------------------------------------------------------- */
export function CommandsPage() {
  const { can } = useAuth();
  const c = useCrud("commands", "/api/commands");
  const [edit, setEdit] = useState<any>(null);
  const cols: Column<any>[] = [
    { key: "name", header: "Command", render: (r) => <><code>{r.name}</code>{r.is_system && <span className="badge outline" style={{ marginLeft: 6 }}>Built-in</span>}</> },
    { key: "command_line", header: "Command line", render: (r) => <span className="mono small">{r.command_line}</span> },
    { key: "description", header: "Description" },
    { key: "a", header: "", sortable: false, className: "actions", render: (r) => <RowButtons canEdit={can("catalog.manage") && !r.is_system} canDelete={can("catalog.manage") && !r.is_system} onEdit={() => setEdit(r)} onDelete={() => c.remove(r, r.name)} /> },
  ];
  return (
    <div>
      <PageHeader title="Commands" subtitle="Portal-managed Nagios command definitions. {NMP} and {STD} expand to the configured plugin directories." actions={can("catalog.manage") && <button className="btn primary" onClick={() => setEdit({})}><Plus size={15} />New command</button>} />
      <Card flush>{c.q.isLoading ? <Loading /> : <DataTable rows={c.rows} columns={cols} rowKey={(r) => r.id} />}</Card>
      {edit && <CommandForm item={edit} onClose={() => setEdit(null)} save={c.save} />}
    </div>
  );
}
function CommandForm({ item, onClose, save }: any) {
  const [v, setV] = useState({ name: item.name ?? "", command_line: item.command_line ?? "$USER1$/", description: item.description ?? "" });
  return (
    <EditModal size="wide" title={item.id ? `Edit ${item.name}` : "New command"} onClose={onClose} onSave={() => save(item, { ...v, description: v.description || null })}>
      <Alert kind="info">Commands must start with an approved plugin directory ($USER1$/, the standard plugin directory or the portal plugin directory). Shell operators (; && || ` $( &gt; &lt;) are rejected.</Alert>
      <Field label="Name" required><input className="input" disabled={!!item.id} value={v.name} onChange={(e) => setV({ ...v, name: e.target.value })} /></Field>
      <Field label="Command line" required><input className="input mono" value={v.command_line} onChange={(e) => setV({ ...v, command_line: e.target.value })} /></Field>
      <Field label="Description"><input className="input" value={v.description} onChange={(e) => setV({ ...v, description: e.target.value })} /></Field>
    </EditModal>
  );
}

/* Contacts ------------------------------------------------------------------ */
export function ContactsPage() {
  const { can } = useAuth();
  const c = useCrud("contacts", "/api/contacts");
  const [edit, setEdit] = useState<any>(null);
  const cols: Column<any>[] = [
    { key: "name", header: "Name" }, { key: "alias", header: "Alias" }, { key: "email", header: "E-mail" }, { key: "phone", header: "Phone" },
    { key: "opts", header: "Host / service options", sortable: false, render: (r) => <span className="mono small">{r.host_notification_options} / {r.service_notification_options}</span> },
    { key: "notification_period", header: "Period" },
    { key: "is_enabled", header: "Enabled", render: (r) => (r.is_enabled ? "Yes" : "No") }, { key: "is_managed", header: "Managed by", render: (r) => <Managed v={r.is_managed} /> },
    { key: "a", header: "", sortable: false, className: "actions", render: (r) => <RowButtons canEdit={can("contacts.manage") && r.is_managed} canDelete={can("contacts.manage")} onEdit={() => setEdit(r)} onDelete={() => c.remove(r, r.name)} /> },
  ];
  return (
    <div>
      <PageHeader title="Contacts" subtitle="Nagios contacts used for Nagios' own notifications." actions={can("contacts.manage") && <button className="btn primary" onClick={() => setEdit({})}><Plus size={15} />New contact</button>} />
      <Card flush>{c.q.isLoading ? <Loading /> : <DataTable rows={c.rows} columns={cols} rowKey={(r) => r.id} />}</Card>
      {edit && <ContactForm item={edit} onClose={() => setEdit(null)} save={c.save} />}
    </div>
  );
}
function ContactForm({ item, onClose, save }: any) {
  const [v, setV] = useState({ name: item.name ?? "", alias: item.alias ?? "", email: item.email ?? "", phone: item.phone ?? "", host_notification_options: item.host_notification_options ?? "d,u,r", service_notification_options: item.service_notification_options ?? "w,u,c,r", notification_period: item.notification_period ?? "24x7", is_enabled: item.is_enabled ?? true });
  const [err] = useState<unknown>(null);
  return (
    <EditModal title={item.id ? `Edit ${item.name}` : "New contact"} onClose={onClose} onSave={() => save(item, { ...v, email: v.email || null, phone: v.phone || null })}>
      <div className="form-grid">
        <Field label="Name" required error={fe(err, "name")}><input className="input" disabled={!!item.id} value={v.name} onChange={(e) => setV({ ...v, name: e.target.value })} /></Field>
        <Field label="Alias" required><input className="input" value={v.alias} onChange={(e) => setV({ ...v, alias: e.target.value })} /></Field>
        <Field label="E-mail"><input className="input" type="email" value={v.email} onChange={(e) => setV({ ...v, email: e.target.value })} /></Field>
        <Field label="Phone / pager"><input className="input" value={v.phone} onChange={(e) => setV({ ...v, phone: e.target.value })} /></Field>
        <Field label="Host notification options" hint="d,u,r,f,s or n"><input className="input" value={v.host_notification_options} onChange={(e) => setV({ ...v, host_notification_options: e.target.value })} /></Field>
        <Field label="Service notification options" hint="w,u,c,r,f,s or n"><input className="input" value={v.service_notification_options} onChange={(e) => setV({ ...v, service_notification_options: e.target.value })} /></Field>
        <Field label="Notification period"><input className="input" value={v.notification_period} onChange={(e) => setV({ ...v, notification_period: e.target.value })} /></Field>
        <Field label="Status"><Checkbox checked={v.is_enabled} onChange={(c) => setV({ ...v, is_enabled: c })} label="Notifications enabled" /></Field>
      </div>
    </EditModal>
  );
}

export function ContactGroupsPage() {
  const { can } = useAuth();
  const c = useCrud("contact-groups", "/api/contact-groups");
  const contacts = useQuery({ queryKey: ["contacts"], queryFn: () => api.get("/api/contacts") });
  const [edit, setEdit] = useState<any>(null);
  const cols: Column<any>[] = [
    { key: "name", header: "Name" }, { key: "alias", header: "Alias" },
    { key: "members", header: "Members", sortable: false, render: (r) => r.members.map((m: any) => <span className="tag" key={m.id}>{m.name}</span>) },
    { key: "is_managed", header: "Managed by", render: (r) => <Managed v={r.is_managed} /> },
    { key: "a", header: "", sortable: false, className: "actions", render: (r) => <RowButtons canEdit={can("contacts.manage") && r.is_managed} canDelete={can("contacts.manage")} onEdit={() => setEdit(r)} onDelete={() => c.remove(r, r.name)} /> },
  ];
  return (
    <div>
      <PageHeader title="Contact groups" actions={can("contacts.manage") && <button className="btn primary" onClick={() => setEdit({ members: [] })}><Plus size={15} />New contact group</button>} />
      <Card flush>{c.q.isLoading ? <Loading /> : <DataTable rows={c.rows} columns={cols} rowKey={(r) => r.id} />}</Card>
      {edit && <CGroupForm item={edit} contacts={contacts.data?.data ?? []} onClose={() => setEdit(null)} save={c.save} />}
    </div>
  );
}
function CGroupForm({ item, contacts, onClose, save }: any) {
  const [v, setV] = useState({ name: item.name ?? "", alias: item.alias ?? "", member_ids: item.members.map((m: any) => m.id) });
  return (
    <EditModal title={item.id ? `Edit ${item.name}` : "New contact group"} onClose={onClose} onSave={() => save(item, v)}>
      <Field label="Name" required><input className="input" disabled={!!item.id} value={v.name} onChange={(e) => setV({ ...v, name: e.target.value })} /></Field>
      <Field label="Alias" required><input className="input" value={v.alias} onChange={(e) => setV({ ...v, alias: e.target.value })} /></Field>
      <Field label="Members"><div className="row">{contacts.map((ct: any) => <Checkbox key={ct.id} checked={v.member_ids.includes(ct.id)} label={ct.name} onChange={(c) => setV({ ...v, member_ids: c ? [...v.member_ids, ct.id] : v.member_ids.filter((x: number) => x !== ct.id) })} />)}</div></Field>
    </EditModal>
  );
}
