"""initial schema - users/RBAC, inventory, catalog, templates, versions, audit, notifications, perf

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 04:43:26.606923
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql  # noqa: F401

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitor_state_cache',
    sa.Column('object_key', sa.String(length=190), nullable=False),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('object_key')
    )
    op.create_table('perf_samples',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('service_description', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('uom', sa.String(length=16), nullable=True),
    sa.Column('warn', sa.Float(), nullable=True),
    sa.Column('crit', sa.Float(), nullable=True),
    sa.Column('sampled_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'service_description', 'label', 'sampled_at', name='uq_perf_sample')
    )
    op.create_index('ix_perf_lookup', 'perf_samples', ['server_id', 'service_description', 'sampled_at'], unique=False)
    op.create_index('ix_perf_time', 'perf_samples', ['sampled_at'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('rate_limit_buckets',
    sa.Column('bucket_key', sa.String(length=190), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('bucket_key')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=190), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('worker_heartbeat',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('entity_name', sa.String(length=190), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('result', sa.Enum('success', 'failure', 'denied', name='audit_result'), nullable=False),
    sa.Column('detail', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_time', 'audit_logs', ['occurred_at'], unique=False)
    op.create_index('ix_audit_user', 'audit_logs', ['user_id'], unique=False)
    op.create_table('commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('command_line', sa.String(length=1024), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('config_backups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('files', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('contact_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('alias', sa.String(length=120), nullable=False),
    sa.Column('is_managed', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('alias', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=190), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('host_notification_options', sa.String(length=20), nullable=False),
    sa.Column('service_notification_options', sa.String(length=20), nullable=False),
    sa.Column('notification_period', sa.String(length=64), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_managed', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('monitoring_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('os_type', sa.Enum('windows', 'linux', 'unix', 'network', 'other', name='os_type'), nullable=False),
    sa.Column('monitoring_method', sa.Enum('ncpa', 'snmp', 'nrpe', 'ping', 'custom', name='mon_method'), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('notification_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('secret_ciphertext', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('server_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('alias', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_managed', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('configuration_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('summary', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('generated', 'validation_failed', 'validated', 'applying', 'applied', 'apply_failed', 'rolled_back', 'superseded', name='version_status'), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=True),
    sa.Column('validation_output', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mariadb').with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('validation_warnings', sa.JSON(), nullable=True),
    sa.Column('apply_log', sa.JSON(), nullable=True),
    sa.Column('backup_id', sa.Integer(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('applied_by', sa.Integer(), nullable=True),
    sa.Column('rollback_of_version', sa.Integer(), nullable=True),
    sa.Column('snapshot', sa.LargeBinary().with_variant(mysql.LONGBLOB(), 'mariadb').with_variant(mysql.LONGBLOB(), 'mysql'), nullable=True),
    sa.Column('legacy_overrides', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['applied_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['backup_id'], ['config_backups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuration_versions_created_at'), 'configuration_versions', ['created_at'], unique=False)
    op.create_table('contact_group_members',
    sa.Column('contact_group_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_group_id'], ['contact_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contact_group_id', 'contact_id')
    )
    op.create_table('notification_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('event_types', sa.JSON(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('throttle_minutes', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['notification_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('environment', sa.Enum('production', 'uat', 'development', 'dr', 'test', name='environment'), nullable=False),
    sa.Column('os_type', sa.Enum('windows', 'linux', 'unix', 'network', 'other', name='os_type'), nullable=False),
    sa.Column('os_version', sa.String(length=120), nullable=True),
    sa.Column('device_type', sa.Enum('server', 'network_device', name='device_type'), nullable=False),
    sa.Column('monitoring_method', sa.Enum('ncpa', 'snmp', 'nrpe', 'ping', 'custom', name='mon_method'), nullable=False),
    sa.Column('host_check', sa.String(length=16), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('check_interval', sa.Integer(), nullable=False),
    sa.Column('retry_interval', sa.Integer(), nullable=False),
    sa.Column('max_check_attempts', sa.Integer(), nullable=False),
    sa.Column('notification_interval', sa.Integer(), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('check_period', sa.String(length=64), nullable=False),
    sa.Column('notification_period', sa.String(length=64), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('config_state', sa.Enum('draft', 'pending', 'applied', 'error', name='config_state'), nullable=False),
    sa.Column('managed_by', sa.Enum('portal', 'external', name='managed_by'), nullable=False),
    sa.Column('imported_from', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_token', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['monitoring_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname', 'deleted_token', name='uq_server_hostname')
    )
    op.create_index('ix_server_env', 'servers', ['environment'], unique=False)
    op.create_index('ix_server_os', 'servers', ['os_type'], unique=False)
    op.create_index('ix_server_state', 'servers', ['config_state'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('monitoring_method', sa.Enum('ncpa', 'snmp', 'nrpe', 'ping', 'custom', name='mon_method'), nullable=False),
    sa.Column('os_types', sa.JSON(), nullable=False),
    sa.Column('command_id', sa.Integer(), nullable=False),
    sa.Column('arg_template', sa.String(length=512), nullable=False),
    sa.Column('params_schema', sa.JSON(), nullable=False),
    sa.Column('default_description', sa.String(length=100), nullable=False),
    sa.Column('default_warning', sa.String(length=40), nullable=True),
    sa.Column('default_critical', sa.String(length=40), nullable=True),
    sa.Column('default_check_interval', sa.Integer(), nullable=False),
    sa.Column('default_retry_interval', sa.Integer(), nullable=False),
    sa.Column('default_notification_interval', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['command_id'], ['commands.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('configuration_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('entity_name', sa.String(length=190), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['configuration_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_change_pending', 'configuration_changes', ['version_id', 'created_at'], unique=False)
    op.create_table('configuration_version_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mariadb').with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['configuration_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'path', name='uq_version_file')
    )
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('object_key', sa.String(length=190), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.String(length=512), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['notification_channels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['notification_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notif_throttle', 'notifications', ['rule_id', 'object_key', 'created_at'], unique=False)
    op.create_index('ix_notif_time', 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_server_id'), 'notifications', ['server_id'], unique=False)
    op.create_table('server_contact_groups',
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('contact_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_group_id'], ['contact_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('server_id', 'contact_group_id')
    )
    op.create_table('server_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('credential_type', sa.Enum('ncpa', 'snmp', 'nrpe', 'custom', name='cred_type'), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('ssl_enabled', sa.Boolean(), nullable=False),
    sa.Column('verify_ssl', sa.Boolean(), nullable=False),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('snmp_version', sa.String(length=8), nullable=True),
    sa.Column('snmp_username', sa.String(length=64), nullable=True),
    sa.Column('snmp_auth_protocol', sa.String(length=16), nullable=True),
    sa.Column('snmp_priv_protocol', sa.String(length=16), nullable=True),
    sa.Column('snmp_security_level', sa.String(length=16), nullable=True),
    sa.Column('secret_ciphertext', sa.Text(), nullable=True),
    sa.Column('last_test_at', sa.DateTime(), nullable=True),
    sa.Column('last_test_result', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'credential_type', name='uq_server_cred_type')
    )
    op.create_table('server_group_members',
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['server_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('server_id', 'group_id')
    )
    op.create_table('server_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('service_description', sa.String(length=100), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('from_template_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_template_id'], ['monitoring_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'service_description', name='uq_server_svc_desc')
    )
    op.create_table('template_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('service_description', sa.String(length=100), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('warning', sa.String(length=40), nullable=True),
    sa.Column('critical', sa.String(length=40), nullable=True),
    sa.Column('check_interval', sa.Integer(), nullable=True),
    sa.Column('retry_interval', sa.Integer(), nullable=True),
    sa.Column('notification_interval', sa.Integer(), nullable=True),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['monitoring_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'service_description', name='uq_tpl_svc_desc')
    )
    op.create_table('service_thresholds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_service_id', sa.Integer(), nullable=False),
    sa.Column('warning', sa.String(length=40), nullable=True),
    sa.Column('critical', sa.String(length=40), nullable=True),
    sa.Column('check_interval', sa.Integer(), nullable=False),
    sa.Column('retry_interval', sa.Integer(), nullable=False),
    sa.Column('max_check_attempts', sa.Integer(), nullable=False),
    sa.Column('notification_interval', sa.Integer(), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['server_service_id'], ['server_services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_service_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_thresholds')
    op.drop_table('template_services')
    op.drop_table('server_services')
    op.drop_table('server_group_members')
    op.drop_table('server_credentials')
    op.drop_table('server_contact_groups')
    op.drop_index(op.f('ix_notifications_server_id'), table_name='notifications')
    op.drop_index('ix_notif_time', table_name='notifications')
    op.drop_index('ix_notif_throttle', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('configuration_version_files')
    op.drop_index('ix_change_pending', table_name='configuration_changes')
    op.drop_table('configuration_changes')
    op.drop_table('services')
    op.drop_index('ix_server_state', table_name='servers')
    op.drop_index('ix_server_os', table_name='servers')
    op.drop_index('ix_server_env', table_name='servers')
    op.drop_table('servers')
    op.drop_table('notification_rules')
    op.drop_table('contact_group_members')
    op.drop_index(op.f('ix_configuration_versions_created_at'), table_name='configuration_versions')
    op.drop_table('configuration_versions')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('user_roles')
    op.drop_table('system_settings')
    op.drop_table('server_groups')
    op.drop_table('role_permissions')
    op.drop_table('notification_channels')
    op.drop_table('monitoring_templates')
    op.drop_table('contacts')
    op.drop_table('contact_groups')
    op.drop_table('config_backups')
    op.drop_table('commands')
    op.drop_index('ix_audit_user', table_name='audit_logs')
    op.drop_index('ix_audit_time', table_name='audit_logs')
    op.drop_index('ix_audit_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('worker_heartbeat')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('rate_limit_buckets')
    op.drop_table('permissions')
    op.drop_index('ix_perf_time', table_name='perf_samples')
    op.drop_index('ix_perf_lookup', table_name='perf_samples')
    op.drop_table('perf_samples')
    op.drop_table('monitor_state_cache')
    # ### end Alembic commands ###
